name: End_to_End_Workflow
on: workflow_dispatch
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Step 1 
        run: echo "whoami"
      - name: Print Step 2
        run: echo "id"
     
